name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.1.3, 3.0.5, 2.7.7]

    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: sudo apt-get install libsasl2-dev

      - name: Install gems
        run: bundle install

      - name: Run tests
        run: bundle exec rake test

      - name: Install appraisals
        run: bundle exec appraisal install

      - name: Run appraisals
        run: bundle exec appraisal rake test

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
