name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-arm
            ruby-version: 3.4.1
          - os: ubuntu-latest
            ruby-version: 3.3.6
          - os: ubuntu-20.04
            ruby-version: 3.2.5
          - os: ubuntu-20.04
            ruby-version: 3.1.6

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Start containers
        run: docker compose -f docker-compose.yml up -d

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: sudo apt-get install libsasl2-dev libmysqlclient-dev

      - name: Install gems
        run: bundle install

      - name: Run tests
        run: bundle exec rake test

      - name: Install appraisals
        run: bundle exec appraisal install

      - name: Run appraisals
        run: bundle exec appraisal rake test

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down
